### ISSUE TITLE
Issues Added then Deleted?

### ISSUE THREAD

**Issue by macinjosh** [devondragon/jira-omnifocus#30]
This project is really awesome but I am having a perplexing problem with it. Script seems to run fine, issues are added to OmniFocus but once they are added they start disappearing and by the time the script is done running OmniFocus is back to where it was before I ran the script. No issues are in the Completed perspective either.

**Comment by lgrassini** [comment]
Hi @macinjosh, I used to have the same issue. The problem probably is that you have set in your .jofsync.yaml a different username than the your proper username in Jira. Maybe you set your login email instead of the username.

That will cause the following condition to match and consequently to delete the task

`           assignee = data["fields"]["assignee"]["name"].downcase
              if assignee != $opts[:username].downcase
              omnifocus_document.delete task
            end`

**Comment by macinjosh** [comment]
@lgrassini You nailed it! That did the trick, thanks a ton.
