### ISSUE TITLE
Support Nested Default Context/Projects

### ISSUE THREAD

**Issue by devondragon** [devondragon/jira-omnifocus#36]
From an email from Matt W. - 

>  I had a little bit of trouble when I first set it up because I tried to assign the default context / project to a nested value.  For example, I tried to use the context "Office : Computer" (where Computer is a sub-context of Office).  This led to an error running the script.  I changed it just "Computer" and it seemed to work.  However, I'm thinking this works sort of by accident because I have two contexts named "Computer", one nested under "Office" and one under "Home".  Just wondering if there's another syntax for doing this.  If this type of setup just isn't supported, that's fine, just checking if I'm missing something.

**Comment by wallacms** [comment]
I looked into this a bit - digging into the Applescript for OF, it looks like contexts all have a name and a container.  If context is not nested it's containing context is the context called "OmniFocus" and otherwise it is the context that contains it.  I don't think there is any special support in the OF Applescript API for looking up nested contexts/projects.  So my thinking on how to fix this is to support the same syntax that OF does internally: use a colon to represent nesting.  I think OF is somewhat picky about whitespace (i.e it either requires spaces before/after the colon or it doesn't, I don't remember) but I'd propose not doing that here.  So we'd modify the Ruby code to parse the relevant config variable into a tree of contexts and then look up the contexts that match.  If that seems like a reasonable approach, I'll work on a patch and submit a PR.

**Comment by devondragon** [comment]
@wallacms that sounds great!  I really appreciate your willingness to help out!!

**Comment by devondragon** [comment]
Going to close this for now.  Would still love to see a PR from @wallacms if he/she has time to work on this one!
